import { User, Recipe, Like, Rating, Comment, Ingredient, Step } from "./types";

const DAY = 86400000;
const now = Date.now();

export const seedUsers: User[] = [
  {
    id: "u-admin",
    name: "Admin Kulinara",
    email: "admin@kulinara.id",
    password: "admin123",
    role: "admin",
    status: "active",
    emailVerified: true,
    verifyCode: null,
    createdAt: now - 200 * DAY,
  },
  {
    id: "u-sari",
    name: "Sari Amelia",
    email: "sari@contoh.id",
    password: "sari123",
    role: "user",
    status: "active",
    emailVerified: true,
    verifyCode: null,
    createdAt: now - 180 * DAY,
  },
  {
    id: "u-budi",
    name: "Budi Santoso",
    email: "budi@contoh.id",
    password: "budi123",
    role: "user",
    status: "active",
    emailVerified: true,
    verifyCode: null,
    createdAt: now - 160 * DAY,
  },
  {
    id: "u-rina",
    name: "Rina Wulandari",
    email: "rina@contoh.id",
    password: "rina123",
    role: "user",
    status: "active",
    emailVerified: true,
    verifyCode: null,
    createdAt: now - 140 * DAY,
  },
];

function ing(name: string, qty: number | null, unit: string | null, secukupnya = false): Ingredient {
  return { id: `${name}-${unit}-${Math.random()}`, name, qty, unit, secukupnya };
}
function step(n: number, text: string): Step {
  return { id: `s-${n}-${Math.random()}`, n, text };
}

export const seedRecipes: Recipe[] = [
  {
    id: "r-nasgor",
    userId: "u-sari",
    title: "Nasi Goreng Kampung",
    category: "Makanan",
    imageDataUrl: "/recipes/nasi-goreng.jpg",
    placeholderIndex: 0,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Mudah",
    estimatedCost: 18000,
    notes: "Pakai nasi yang sudah dingin (nasi kemarin) supaya hasilnya lebih pera dan tidak lembek.",
    ingredients: [
      ing("Nasi putih", 2, "gelas"),
      ing("Telur", 2, "butir"),
      ing("Bawang merah", 5, "siung"),
      ing("Bawang putih", 3, "siung"),
      ing("Cabai rawit", 5, "buah"),
      ing("Kecap manis", 3, "sdm"),
      ing("Garam", null, null, true),
    ],
    steps: [
      step(1, "Tumis bawang merah, bawang putih, dan cabai rawit yang sudah diiris hingga harum."),
      step(2, "Masukkan telur, orak-arik hingga matang."),
      step(3, "Masukkan nasi putih, aduk rata dengan bumbu."),
      step(4, "Tambahkan kecap manis dan garam secukupnya, masak sambil diaduk selama 5 menit."),
      step(5, "Sajikan selagi hangat dengan pelengkap sesuai selera."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 40 * DAY,
  },
  {
    id: "r-rendang",
    userId: "u-budi",
    title: "Rendang Daging Sapi",
    category: "Makanan",
    imageDataUrl: "/recipes/rendang.jpg",
    placeholderIndex: 1,
    cookTimeMinutes: 180,
    servings: 6,
    difficulty: "Sulit",
    estimatedCost: 120000,
    notes: "Aduk terus di 30 menit terakhir supaya santan tidak pecah dan bumbu meresap sempurna.",
    ingredients: [
      ing("Daging sapi", 1, "kg"),
      ing("Santan kental", 1.5, "liter"),
      ing("Cabai merah keriting", 15, "buah"),
      ing("Bawang merah", 10, "siung"),
      ing("Bawang putih", 6, "siung"),
      ing("Lengkuas", 1, "potong"),
      ing("Daun jeruk", 5, "lembar"),
      ing("Serai", 2, "potong"),
      ing("Garam", null, null, true),
    ],
    steps: [
      step(1, "Haluskan cabai, bawang merah, dan bawang putih."),
      step(2, "Tumis bumbu halus bersama lengkuas, serai, dan daun jeruk hingga harum."),
      step(3, "Masukkan daging sapi, aduk hingga berubah warna."),
      step(4, "Tuang santan, masak dengan api kecil sambil sesekali diaduk selama 2-3 jam."),
      step(5, "Masak hingga kuah mengental dan berminyak, koreksi rasa dengan garam."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 90 * DAY,
  },
  {
    id: "r-supayam",
    userId: "u-rina",
    title: "Sup Ayam Jamur",
    category: "Makanan",
    imageDataUrl: "/recipes/sup-ayam.jpg",
    placeholderIndex: 2,
    cookTimeMinutes: 35,
    servings: 4,
    difficulty: "Mudah",
    estimatedCost: 30000,
    notes: "Bisa diganti dengan jamur kancing kalau jamur kuping tidak tersedia.",
    ingredients: [
      ing("Ayam", 500, "gram"),
      ing("Jamur kuping", 100, "gram"),
      ing("Wortel", 2, "buah"),
      ing("Daun bawang", 2, "lembar"),
      ing("Bawang putih", 3, "siung"),
      ing("Merica", null, null, true),
      ing("Garam", null, null, true),
    ],
    steps: [
      step(1, "Rebus ayam hingga empuk, sisihkan kaldunya."),
      step(2, "Tumis bawang putih hingga harum, masukkan ke kaldu ayam."),
      step(3, "Masukkan wortel dan jamur kuping, masak hingga wortel empuk."),
      step(4, "Bumbui dengan merica dan garam secukupnya."),
      step(5, "Taburi daun bawang sebelum disajikan."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 25 * DAY,
  },
  {
    id: "r-risoles",
    userId: "u-sari",
    title: "Risoles Mayo",
    category: "Camilan",
    imageDataUrl: "/recipes/risoles.jpg",
    placeholderIndex: 3,
    cookTimeMinutes: 60,
    servings: 15,
    difficulty: "Sedang",
    estimatedCost: 35000,
    notes: "Gulung kulit rapat-rapat supaya isian tidak keluar saat digoreng.",
    ingredients: [
      ing("Tepung terigu", 250, "gram"),
      ing("Telur", 2, "butir"),
      ing("Susu cair", 500, "ml"),
      ing("Sosis", 8, "buah"),
      ing("Mayones", 5, "sdm"),
      ing("Tepung roti", 200, "gram"),
    ],
    steps: [
      step(1, "Campur tepung terigu, telur, dan susu cair, aduk hingga tidak bergerindil."),
      step(2, "Buat kulit dadar tipis di atas teflon."),
      step(3, "Isi kulit dengan sosis dan mayones, lipat menjadi amplop."),
      step(4, "Celupkan ke telur kocok lalu balut tepung roti."),
      step(5, "Goreng hingga keemasan dengan api sedang."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 55 * DAY,
  },
  {
    id: "r-pisgor",
    userId: "u-budi",
    title: "Pisang Goreng Crispy",
    category: "Camilan",
    imageDataUrl: "/recipes/pisang-goreng.jpg",
    placeholderIndex: 4,
    cookTimeMinutes: 25,
    servings: 4,
    difficulty: "Mudah",
    estimatedCost: 15000,
    notes: "Gunakan pisang kepok yang sudah matang supaya rasanya manis alami.",
    ingredients: [
      ing("Pisang kepok", 6, "buah"),
      ing("Tepung beras", 100, "gram"),
      ing("Tepung terigu", 50, "gram"),
      ing("Air es", 150, "ml"),
      ing("Garam", null, null, true),
      ing("Minyak goreng", null, null, true),
    ],
    steps: [
      step(1, "Campur tepung beras, tepung terigu, garam, dan air es hingga jadi adonan encer."),
      step(2, "Belah pisang menjadi dua atau tiga bagian memanjang."),
      step(3, "Celupkan pisang ke dalam adonan tepung."),
      step(4, "Goreng dalam minyak panas hingga keemasan dan renyah."),
      step(5, "Tiriskan dan sajikan hangat."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 15 * DAY,
  },
  {
    id: "r-klepon",
    userId: "u-sari",
    title: "Klepon Pandan",
    category: "Camilan",
    imageDataUrl: "/recipes/klepon.jpg",
    placeholderIndex: 5,
    cookTimeMinutes: 45,
    servings: 20,
    difficulty: "Sedang",
    estimatedCost: 22000,
    notes: "Rebus klepon hingga mengapung penuh supaya matang merata sampai ke tengah.",
    ingredients: [
      ing("Tepung ketan", 250, "gram"),
      ing("Air daun suji", 180, "ml"),
      ing("Gula merah", 150, "gram"),
      ing("Kelapa parut", 1, "buah"),
      ing("Garam", null, null, true),
    ],
    steps: [
      step(1, "Campur tepung ketan dengan air daun suji hingga adonan bisa dipulung."),
      step(2, "Kukus kelapa parut dengan sedikit garam, sisihkan."),
      step(3, "Ambil adonan, pipihkan, isi dengan gula merah sisir, bulatkan."),
      step(4, "Rebus bulatan dalam air mendidih hingga mengapung."),
      step(5, "Gulingkan klepon matang di atas kelapa parut kukus."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 10 * DAY,
  },
  {
    id: "r-esteh",
    userId: "u-rina",
    title: "Es Teh Manis Segar",
    category: "Minuman",
    imageDataUrl: "/recipes/es-teh.jpg",
    placeholderIndex: 0,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: "Mudah",
    estimatedCost: 5000,
    notes: "Seduh teh dengan air panas dulu baru diberi es, supaya rasa tehnya keluar maksimal.",
    ingredients: [
      ing("Teh celup", 2, "buah"),
      ing("Air panas", 300, "ml"),
      ing("Gula pasir", 4, "sdm"),
      ing("Es batu", null, null, true),
    ],
    steps: [
      step(1, "Seduh teh celup dengan air panas selama 5 menit."),
      step(2, "Larutkan gula pasir ke dalam air teh panas, aduk rata."),
      step(3, "Tuang ke gelas berisi es batu."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 30 * DAY,
  },
  {
    id: "r-cendol",
    userId: "u-sari",
    title: "Es Cendol Durian",
    category: "Minuman",
    imageDataUrl: "/recipes/es-cendol.jpg",
    placeholderIndex: 1,
    cookTimeMinutes: 40,
    servings: 4,
    difficulty: "Sedang",
    estimatedCost: 28000,
    notes: "Bisa diganti durian beku kalau tidak musim, hasilnya tetap creamy.",
    ingredients: [
      ing("Cendol", 200, "gram"),
      ing("Santan kental", 400, "ml"),
      ing("Gula merah cair", 150, "ml"),
      ing("Daging durian", 100, "gram"),
      ing("Es serut", null, null, true),
    ],
    steps: [
      step(1, "Siapkan gelas saji, masukkan cendol di dasar gelas."),
      step(2, "Tambahkan gula merah cair secukupnya."),
      step(3, "Tuang santan kental di atasnya."),
      step(4, "Tambahkan daging durian dan es serut."),
      step(5, "Sajikan segera selagi dingin."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 20 * DAY,
  },
  {
    id: "r-puding",
    userId: "u-budi",
    title: "Puding Coklat Lumer",
    category: "Kue & Dessert",
    imageDataUrl: "/recipes/puding-coklat.jpg",
    placeholderIndex: 2,
    cookTimeMinutes: 50,
    servings: 6,
    difficulty: "Sedang",
    estimatedCost: 32000,
    notes: "Dinginkan minimal 2 jam di kulkas supaya teksturnya set sempurna sebelum disajikan.",
    ingredients: [
      ing("Bubuk agar-agar coklat", 2, "sdm"),
      ing("Susu cair", 500, "ml"),
      ing("Coklat batang", 100, "gram"),
      ing("Gula pasir", 80, "gram"),
      ing("Telur", 2, "butir"),
    ],
    steps: [
      step(1, "Lelehkan coklat batang dengan sedikit susu cair."),
      step(2, "Campur bubuk agar-agar, sisa susu cair, dan gula pasir, masak sambil diaduk."),
      step(3, "Masukkan coklat leleh, aduk rata hingga mendidih."),
      step(4, "Tuang ke cetakan, biarkan dingin di suhu ruang."),
      step(5, "Simpan di kulkas minimal 2 jam sebelum disajikan."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 12 * DAY,
  },
  {
    id: "r-lapislegit",
    userId: "u-rina",
    title: "Kue Lapis Legit",
    category: "Kue & Dessert",
    imageDataUrl: "/recipes/lapis-legit.jpg",
    placeholderIndex: 3,
    cookTimeMinutes: 150,
    servings: 20,
    difficulty: "Sulit",
    estimatedCost: 95000,
    notes: "Panggang tiap lapisan dengan api atas saja supaya motif lapisannya rapi.",
    ingredients: [
      ing("Mentega", 500, "gram"),
      ing("Gula halus", 300, "gram"),
      ing("Kuning telur", 20, "butir"),
      ing("Tepung terigu", 100, "gram"),
      ing("Bumbu spekuk", 1, "sdm"),
      ing("Susu kental manis", 3, "sdm"),
    ],
    steps: [
      step(1, "Kocok mentega dan gula halus hingga pucat dan lembut."),
      step(2, "Masukkan kuning telur satu per satu sambil terus dikocok."),
      step(3, "Masukkan tepung terigu dan bumbu spekuk, aduk perlahan."),
      step(4, "Tuang adonan tipis per lapis ke loyang, panggang tiap lapisan hingga matang."),
      step(5, "Ulangi hingga adonan habis, dinginkan sebelum dipotong."),
    ],
    isPublic: true,
    forkedFromId: null,
    createdAt: now - 70 * DAY,
  },
];

export const seedLikes: Like[] = [
  { userId: "u-budi", recipeId: "r-nasgor", createdAt: now - 5 * DAY },
  { userId: "u-rina", recipeId: "r-nasgor", createdAt: now - 4 * DAY },
  { userId: "u-sari", recipeId: "r-rendang", createdAt: now - 20 * DAY },
  { userId: "u-rina", recipeId: "r-rendang", createdAt: now - 18 * DAY },
  { userId: "u-admin", recipeId: "r-rendang", createdAt: now - 15 * DAY },
  { userId: "u-budi", recipeId: "r-cendol", createdAt: now - 10 * DAY },
  { userId: "u-rina", recipeId: "r-cendol", createdAt: now - 9 * DAY },
  { userId: "u-sari", recipeId: "r-puding", createdAt: now - 6 * DAY },
];

export const seedRatings: Rating[] = [
  { id: "rt-1", userId: "u-budi", recipeId: "r-nasgor", stars: 5, photoDataUrl: null, createdAt: now - 5 * DAY },
  { id: "rt-2", userId: "u-rina", recipeId: "r-nasgor", stars: 4, photoDataUrl: null, createdAt: now - 4 * DAY },
  { id: "rt-3", userId: "u-sari", recipeId: "r-rendang", stars: 5, photoDataUrl: null, createdAt: now - 20 * DAY },
  { id: "rt-4", userId: "u-rina", recipeId: "r-rendang", stars: 5, photoDataUrl: null, createdAt: now - 18 * DAY },
  { id: "rt-5", userId: "u-admin", recipeId: "r-rendang", stars: 4, photoDataUrl: null, createdAt: now - 15 * DAY },
  { id: "rt-6", userId: "u-budi", recipeId: "r-cendol", stars: 5, photoDataUrl: null, createdAt: now - 10 * DAY },
  { id: "rt-7", userId: "u-rina", recipeId: "r-cendol", stars: 4, photoDataUrl: null, createdAt: now - 9 * DAY },
  { id: "rt-8", userId: "u-sari", recipeId: "r-puding", stars: 5, photoDataUrl: null, createdAt: now - 6 * DAY },
  { id: "rt-9", userId: "u-budi", recipeId: "r-supayam", stars: 4, photoDataUrl: null, createdAt: now - 8 * DAY },
  { id: "rt-10", userId: "u-sari", recipeId: "r-lapislegit", stars: 5, photoDataUrl: null, createdAt: now - 40 * DAY },
];

export const seedComments: Comment[] = [
  {
    id: "c-1",
    recipeId: "r-nasgor",
    userId: "u-budi",
    text: "Enak banget, anak-anak suka! Aku tambah sosis juga.",
    createdAt: now - 5 * DAY,
    reported: false,
    reportReason: "",
  },
  {
    id: "c-2",
    recipeId: "r-rendang",
    userId: "u-rina",
    text: "Resep rendang paling autentik yang pernah aku coba, bumbunya pas.",
    createdAt: now - 18 * DAY,
    reported: false,
    reportReason: "",
  },
  {
    id: "c-3",
    recipeId: "r-cendol",
    userId: "u-budi",
    text: "Seger banget buat siang-siang panas gini.",
    createdAt: now - 9 * DAY,
    reported: false,
    reportReason: "",
  },
  {
    id: "c-4",
    recipeId: "r-puding",
    userId: "u-sari",
    text: "Teksturnya lumer di mulut, coklatnya berasa banget.",
    createdAt: now - 6 * DAY,
    reported: false,
    reportReason: "",
  },
];
